<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActivitySeeder extends Seeder
{
   public function run() : void
    {
        DB::table('activities')->insert([
            ['name' => 'Abogados' ],
            ['name' => 'Academias' ],
            ['name' => 'Actividades de Ocio' ],
            ['name' => 'Agencias de Viajes' ],
            ['name' => 'Agricultura' ],
            ['name' => 'Agroganadero' ],
            ['name' => 'Agroindustria' ],
            ['name' => 'Albañiles' ],
            ['name' => 'Armadores' ],
            ['name' => 'Artes Gráficas' ],
            ['name' => 'Asesorías' ],
            ['name' => 'Autobuses' ],
            ['name' => 'Autoescuelas' ],
            ['name' => 'Bancos' ],
            ['name' => 'Bares y Restaurantes' ],
            ['name' => 'Butano' ],
            ['name' => 'Camping' ],
            ['name' => 'Carnicerias' ],
            ['name' => 'Cemento' ],
            ['name' => 'Centros de Estética' ],
            ['name' => 'Comercio' ],
            ['name' => 'Comida Para Llevar' ],
            ['name' => 'Comunicación' ],
            ['name' => 'Concesionarios de Automóviles' ],
            ['name' => 'Confiterías' ],
            ['name' => 'Conservas' ],
            ['name' => 'Construcción' ],
            ['name' => 'Construcciones Metalicas' ],
            ['name' => 'Cooperativas Agroalimentarias' ],
            ['name' => 'Copisterías' ],
            ['name' => 'Dentistas' ],
            ['name' => 'Deporte' ],
            ['name' => 'Drones' ],
            ['name' => 'Droguería' ],
            ['name' => 'Electricistas' ],
            ['name' => 'Eléctricos' ],
            ['name' => 'Enseñanza' ],
            ['name' => 'Farmacias' ],
            ['name' => 'Ferreterías' ],
            ['name' => 'Fisioterapias' ],
            ['name' => 'Floristerías' ],
            ['name' => 'Fontaneros' ],
            ['name' => 'Fotografía' ],
            ['name' => 'Funerarias' ],
            ['name' => 'Gasolineras' ],
            ['name' => 'Gestorías' ],
            ['name' => 'Gimnasios' ],
            ['name' => 'Hamburgueserías' ],
            ['name' => 'Heladerías' ],
            ['name' => 'Hostales' ],
            ['name' => 'Hosteleria' ],
            ['name' => 'Hoteles' ],
            ['name' => 'Hoteles y Casas Rurales' ],
            ['name' => 'Industria' ],
            ['name' => 'Informática' ],
            ['name' => 'Inmobiliarias' ],
            ['name' => 'Jardineros' ],
            ['name' => 'Joyerías' ],
            ['name' => 'Jugueterías' ],
            ['name' => 'Kebaps' ],
            ['name' => 'Laboratorio' ],
            ['name' => 'Lavanderias' ],
            ['name' => 'Librerias' ],
            ['name' => 'Limpiezas' ],
            ['name' => 'Lonja' ],
            ['name' => 'Madera' ],
            ['name' => 'Mantenimiento y Obras' ],
            ['name' => 'Máquinas Recreativas' ],
            ['name' => 'Mensajerías' ],
            ['name' => 'Mercado' ],
            ['name' => 'Minería' ],
            ['name' => 'Mobiliario Y Decoracion' ],
            ['name' => 'Mujeres Empresarias' ],
            ['name' => 'Multisector' ],
            ['name' => 'Multisectorial Local' ],
            ['name' => 'Ocio' ],
            ['name' => 'Oficina de Correos' ],
            ['name' => 'Optica' ],
            ['name' => 'Ortopedicos' ],
            ['name' => 'Panaderías' ],
            ['name' => 'Papelerías' ],
            ['name' => 'Pastelerías' ],
            ['name' => 'Peluquerías' ],
            ['name' => 'Pensiones' ],
            ['name' => 'Pescaderias Y Mariscos' ],
            ['name' => 'Pintores' ],
            ['name' => 'Pizzerías' ],
            ['name' => 'Publicidad' ],
            ['name' => 'Pubs y Discotecas' ],
            ['name' => 'Reparacion de Automóviles' ],
            ['name' => 'Restaurantes Chinos' ],
            ['name' => 'Restaurantes Italiano' ],
            ['name' => 'Restaurantes Indú' ],
            ['name' => 'Restaurantes Japonés' ],
            ['name' => 'Resturantes Mexicano' ],
            ['name' => 'Sanitarias' ],
            ['name' => 'Sector Ambiental' ],
            ['name' => 'Seguridad Privada' ],
            ['name' => 'Seguros' ],
            ['name' => 'Servicios Profesionales' ],
            ['name' => 'Servicios Sociales' ],
            ['name' => 'Servicios Técnicos Telefonía' ],
            ['name' => 'Servicios Turísticos' ],
            ['name' => 'Suministros Industriales' ],
            ['name' => 'Supermercados' ],
            ['name' => 'Taxis' ],
            ['name' => 'Telefonia Móvil' ],
            ['name' => 'Tiendas 24 Horas' ],
            ['name' => 'Tiendas de Moda' ],
            ['name' => 'Toldos' ],
            ['name' => 'Transportes' ],
            ['name' => 'Turismo' ],
            ['name' => 'Veterinarios' ],
            ['name' => 'Vinícolas' ],
            ['name' => 'Zapaterias' ],
        ]);
    }
}
